### ISSUE TITLE
Screen overlay feature is missing

### ISSUE THREAD

**Issue by furqansafdar** [100GPing100/LoadingIndicators.WPF#1]
I couldn't find any built-in ability to overlay the screen or a certain portion of it to make it act like a model dialog, modal-type experience or to block access to a certain portion of the screen while an asynchronous or long running operation is happening. Like given in the following links:
https://wpftoolkit.codeplex.com/wikipage?title=BusyIndicator&referringTitle=Home
http://www.codeproject.com/Articles/57984/WPF-Loading-Wait-Adorner

**Comment by punker76** [comment]
@furqansafdar the loading indicators here are only the loading controls and not a complete blocking dialog or somethong else...

**Comment by 100GPing100** [comment]
Closed as explained by @punker76
